# My aliases
alias ocaml="rlwrap ocaml"
alias ssh='/usr/bin/ssh'
alias ls='ls -G'
alias rmate='mate Rakefile README app bin config doc db lib public script spec test stories features examples'
alias ri='ri -Tf ansi'
alias ss='./script/server'
alias sc='./script/console'
alias vi='/Applications/MacVim.app/Contents/MacOS/Vim -p'
alias vim='/Applications/MacVim.app/Contents/MacOS/Vim -p'
alias postgres_start='pg_ctl -D ~/.pgdata -l ~/.pgdata/psql.log start'
alias postgres_stop='pg_ctl -D ~/.pgdata stop'
alias mysql='/opt/local/bin/mysql5 -u root --socket=/tmp/mysql.sock'
alias mysqladmin='/opt/local/bin/mysqladmin5 -u root --socket=/tmp/mysql.sock'
alias mysql_config='/opt/local/bin/mysql_config5'
alias gvim='mvim -p'
alias cycle_passenger='touch tmp/restart.txt'
alias gemdir='/Library/Ruby/Gems/1.8/gems/'
alias jruby='~/open_source/jruby_install/bin/jruby'
alias espresso='/Applications/Espresso.app/Contents/MacOS/Espresso'
