export MANPATH=/opt/local/share/man:$MANPATH
#export PATH=/usr/local/git/bin:/Library/Ruby/bin:/opt/local/bin:/opt/local/lib/postgresql82/bin/:/opt/local/sbin:/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/:/usr/local/bin:$PATH
export PATH=/opt/ruby-enterprise-1.8.6-20081205/bin:/Users/chad/.gem/ruby/1.8/bin:/usr/local/git/bin:/opt/local/bin:/opt/local/lib/postgresql82/bin/:/opt/local/sbin:/usr/local/bin:$PATH
export JAVA_HOME='/System/Library/Frameworks/JavaVM.framework/Home'
export JRUBY_HOME='~/open_source/jruby_install'
export CDPATH=~/spicycode:~/open_source:~/relevance
export RUBYOPT='rubygems'
export GREP_OPTIONS='--color=auto' 
export GREP_COLOR='3;33'
export EDITOR="vim"
export TERM=xterm-256color
export LSCOLORS=gxfxcxdxbxegedabagacad
export CLICOLOR=1
