export MANPATH=/opt/local/share/man:$MANPATH
export CABAL_BIN="$HOME/.cabal/bin"
export ORIGINAL_PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:$CABAL_BIN:$PATH
export JAVA_HOME='/System/Library/Frameworks/JavaVM.framework/Home'
export JRUBY_HOME='~/open_source/jruby_install'
export CDPATH=.:~/spicycode:~/open_source:~/relevance
export RUBYOPT='rubygems'
export GREP_OPTIONS='--color=auto' 
export GREP_COLOR='3;33'
export EDITOR="vim"
export TERM=xterm-color
export LSCOLORS=gxfxcxdxbxegedabagacad
export CLICOLOR=1
export PAGER="most"
